[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/api/contact"
  status = 200
  to = "/.netlify/functions/api/contact"
  force = true
  from = "/*"
  status = 200
  to = "/index.html"