[build]
  functions = "build/server"
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/api/contact"
  to = "/.netlify/functions/api/contact"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200